refactor: action as a single step

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -41,138 +41,106 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Do preflight checks
-      id: checks
-      shell: bash
-      env:
-        LIX_VERSION: ${{ inputs.lix-version }}
-        # renovate: datasource=github-tags depName=lix-project/lix
-        LIX_DEFAULT_VERSION: 2.91.1
-      run: |
-        :
-        printf '::group::Preflight checks\n'
-        ${{ runner.debug && 'set -x' || '' }}
-        test ! -e /nix -o -w /nix || {
-          printf "::error::failed to set up Lix: /nix exists but isn't writable\n"
-          exit 1
-        }
-        test -n "$LIX_VERSION" || unset LIX_VERSION
-        tee -a "$GITHUB_OUTPUT" <<EOF
-        install-nix-dir=$(test -e /nix || printf 1)
-        our-version=$(cat "$GITHUB_ACTION_PATH"/VERSION)
-        lix-version=${LIX_VERSION:-$LIX_DEFAULT_VERSION}
-        EOF
-        printf '::endgroup::\n'
-    - name: Mount `/nix` directory (Linux)
-      if: ${{ steps.checks.outputs.install-nix-dir && runner.os == 'Linux' }}
-      shell: bash
-      run: |
-        :
-        printf '::group::Mount `/nix` directory\n'
-        ${{ runner.debug && 'set -x' || '' }}
-        sudo install -d -o "$USER" /nix
-        ${{
-          inputs.lix-on-tmpfs &&
-              'sudo mount -t tmpfs -o "size=90%,mode=0755,uid=$UID,gid=$(id -g)" tmpfs /nix' ||
-              ''
-        }}
-        printf '::endgroup::\n'
-    - name: Mount `/nix` directory (macOS)
-      if: ${{ steps.checks.outputs.install-nix-dir && runner.os == 'macOS' }}
-      shell: bash
-      run: |
-        :
-        printf '::group::Mount `/nix` directory\n'
-        ${{ runner.debug && 'set -x' || '' }}
-        sudo tee -a /etc/synthetic.conf <<"EOF"
-        nix
-        run	private/var/run
-        EOF
-        sudo /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t || :
-        test -L /run || {
-          printf "::error::failed to set up Lix: apfs.util couldn't symlink /run\n"
-          exit 1
-        }
-        root_device=$(stat -f %Sd /)
-        sudo diskutil apfs addVolume "${root_device%s*}" APFS nix -mountpoint /nix
-        sudo mdutil -i off /nix
-        sudo chown "$USER" /nix
-        printf '::endgroup::\n'
-    - name: Install Lix store
-      shell: bash
+    - shell: bash
       env:
         GITHUB_TOKEN: ${{ inputs.github-token }}
-        lix_store_url: >-
+        # renovate: datasource=github-tags depName=lix-project/lix
+        LIX_DEFAULT_VERSION: 2.91.0
+        lix_version: ${{ inputs.lix-version }}
+        lix_on_tmpfs: ${{ inputs.lix-on-tmpfs && 'true' || 'false' }}
+        lix_store_base_url: ${{ inputs.lix-store-base-url }}
+        nix_conf: ${{ inputs.nix-conf }}
+        system: >-
           ${{
-            format('{0}/lix-{1}-{2}-{3}.tar.zstd',
-                inputs.lix-store-base-url || format('{0}/{1}/releases/download/v{2}',
-                        github.server_url,
-                        github.action_repository,
-                        steps.checks.outputs.our-version
-                    ),
-                steps.checks.outputs.lix-version,
+            format('{0}-{1}',
                 (runner.arch == 'ARM64' && 'aarch64') || (runner.arch == 'X64' && 'x86_64') || runner.arch,
                 (runner.os == 'Linux' && 'linux') || (runner.os == 'macOS' && 'darwin') || runner.os
             )
           }}
+        tar: ${{ runner.os == 'macOS' && 'gtar' || 'tar' }}
       run: |
         :
-        printf '::group::Install Lix store\n'
         ${{ runner.debug && 'set -x' || '' }}
-        rm -rf /nix/var/action-setup-lix
-        ${{
-          !startsWith(inputs.lix-store-base-url, 'file://') &&
-              'curl --fail --location --remote-name --retry-connrefused --silent --show-error --retry 3 "$lix_store_url"' ||
-              ''
-        }}
-        lix_store_file="${lix_store_url#${{ startsWith(inputs.lix-store-base-url, 'file://') && '*:/' || '#*' }}/}"
-        gh attestation verify "$lix_store_file" --{,signer-}repo="${GITHUB_ACTION_REPOSITORY:-$GITHUB_REPOSITORY}"
-        ${{ runner.os == 'macOS' && 'g' || '' }}tar --auto-compress --extract --skip-old-files --directory=/nix --strip-components=1 <"$lix_store_file"
-        ${{
-          !startsWith(inputs.lix-store-base-url, 'file://') &&
-              'rm -rf "$lix_store_file"' ||
-              ''
-        }}
-        printf '::endgroup::\n'
-    - name: Synthesize `nix.conf`
-      shell: bash
-      env:
-        GITHUB_TOKEN: ${{ inputs.github-token }}
-        nix_conf: ${{ inputs.nix-conf }}
-      run: |
-        :
-        printf '::group::Synthesize `nix.conf`\n'
-        ${{ runner.debug && 'set -x' || '' }}
-        : "${XDG_CONFIG_HOME:=$HOME/.config}"
-        mkdir -p "$XDG_CONFIG_HOME/nix/$GITHUB_REPOSITORY_ID"
-        tee "$XDG_CONFIG_HOME/nix/nix.conf" <<EOF
+
+        group() { printf "::group::%s\n" "$*"; }
+        puorg() { printf "::endgroup::\n"; }
+        error() { printf "::error::%s\n" "$*"; exit 1; }
+
+        group 'Preflight checks'
+          test ! -e /nix -o -w /nix || error "failed to set up Lix: /nix exists but isn't writable"
+
+          : "${GITHUB_ACTION_REPOSITORY:=$GITHUB_REPOSITORY}"
+          : "${XDG_CONFIG_HOME:=$HOME/.config}"
+
+          our_version="$(head -n1 "$GITHUB_ACTION_PATH"/VERSION)"
+          test -n "$lix_version" || lix_version="$LIX_DEFAULT_VERSION"
+          test -n "$lix_store_base_url" ||
+              lix_store_base_url="$GITHUB_SERVER_URL/$GITHUB_ACTION_REPOSITORY/releases/download/v$our_version"
+          lix_store_url="$lix_store_base_url/lix-$lix_version-$system.tar.zstd"
+        puorg
+
+        group 'Mount /nix'
+          if test ! -e /nix; then
+            case "$RUNNER_OS" in
+              Linux)
+                sudo install -d -o "$USER" /nix
+                "$lix_on_tmpfs" && sudo mount -t tmpfs -o "size=90%,mode=0755,uid=$UID,gid=$(id -g)" tmpfs /nix || :
+                ;;
+              macOS)
+                sudo tee -a /etc/synthetic.conf <<<$'nix\nrun\tprivate/var/run\n'
+                sudo /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t || :
+                test -L /run || error "failed to set up Lix: apfs.util couldn't symlink /run"
+                stat -f %Sd / | sed -e 's/s[0-9]*$//' | xargs -I{} -- sudo diskutil apfs addVolume {} APFS nix -mountpoint /nix
+                sudo mdutil -i off /nix
+                sudo chown "$USER" /nix
+                ;;
+              *)
+                error "failed to set up Lix: system $system not supported (yet? :)"
+                ;;
+            esac
+          fi
+        puorg
+
+        group 'Install Lix store'
+          case "$lix_store_url" in
+            file://*)
+              lix_store_file="${lix_store_url#file://}"
+              ;;
+            *)
+              curl --fail --location --remote-name --retry-connrefused --silent --show-error --retry 3 "$lix_store_url"
+              lix_store_file="${lix_store_url##*/}"
+              trap 'rm -f "$lix_store_file"' EXIT
+              ;;
+          esac
+          gh attestation verify "$lix_store_file" --{,signer-}repo="$GITHUB_ACTION_REPOSITORY"
+          rm -rf /nix/var/action-setup-lix
+          "$tar" --auto-compress --extract --skip-old-files --directory /nix --strip-components 1 <"$lix_store_file"
+        puorg
+
+        group 'Synthesize nix.conf'
+          mkdir -p "$XDG_CONFIG_HOME/nix"
+          tee -a "$XDG_CONFIG_HOME/nix/nix.conf" <<EOF
         accept-flake-config = true
         access-tokens = ${GITHUB_SERVER_URL#*://}=$GITHUB_TOKEN
         experimental-features = nix-command flakes
-        include $XDG_CONFIG_HOME/nix/$GITHUB_REPOSITORY_ID/nix.conf
+        include $XDG_CONFIG_HOME/nix/$GITHUB_REPOSITORY_ID.conf
         EOF
-        tee "$XDG_CONFIG_HOME/nix/$GITHUB_REPOSITORY_ID/nix.conf" <<EOF
-        $nix_conf
-        EOF
-        printf '::endgroup::\n'
-    - name: Install Lix
-      shell: bash
-      run: |
-        :
-        printf '::group::Install Lix\n'
-        ${{ runner.debug && 'set -x' || '' }}
-        CDPATH='' cd "$(readlink /nix/var/action-setup-lix/lix)"
-        ./bin/nix-store --load-db </nix/var/action-setup-lix/registration
-        MANPATH='' . ./etc/profile.d/nix.sh
-        : "${NIX_SSL_CERT_FILE:=$(test ! -e /etc/ssl/cert.pem || printf /etc/ssl/cert.pem)}"
-        ./bin/nix-env --install "$PWD"
-        printf %s/.nix-profile/bin\\n "$HOME" >>"$GITHUB_PATH"
-        tee -a "$GITHUB_ENV" <<EOF
+          tee "$XDG_CONFIG_HOME/nix/$GITHUB_REPOSITORY_ID.conf" <<<"$nix_conf"
+        puorg
+
+        group 'Install Lix'
+          CDPATH='' cd "$(readlink /nix/var/action-setup-lix/lix)"
+          ./bin/nix-store --load-db </nix/var/action-setup-lix/registration
+          MANPATH='' . ./etc/profile.d/nix.sh
+          : "${NIX_SSL_CERT_FILE:=$([ ! -e /etc/ssl/cert.pem ] || printf /etc/ssl/cert.pem)}"
+          ./bin/nix-env --install "$PWD"
+          tee -a "$GITHUB_PATH" <<<"$HOME/.nix-profile/bin"
+          tee -a "$GITHUB_ENV" <<EOF
         NIX_PROFILES=/nix/var/nix/profiles/default $HOME/.nix-profile
         NIX_USER_PROFILE_DIR=/nix/var/nix/profiles/per-user/$USER
         NIX_SSL_CERT_FILE=$NIX_SSL_CERT_FILE
         EOF
-        printf '::endgroup::\n'
+        puorg
 branding:
   icon: package
   color: purple
